### PR TITLE
Use httpd_htmlhead_title to control header title

### PR DESCRIPTION
**Pull request by areguera**
- Previously, header.html was showing the title "CentOS Web Style" on
  browser title bar.  This text is not appropriate to all context
  header.html is applied to. This update changes the role to dynamically
  create the header.html file we distribute to target hosts based on a
  template of the same name (header.html.j2) and the value of
  httpd_htmlhead_title variable. By default, this variable is set to
  "CentOS" but can be customized using extra_vars or inside tasks
  themselves (as we did here for people vhost).

- Previously, in people.centos.org vhost, httpd directives like
  +SuppressHTMLPreamble, IndexStyleSheet, HeaderName and ReadmeName were
  considered. However, since we are using an index.html file already
  built with header, users list and footer, such directives are not
  necessary for /var/www/people/ document root. This commit removes them
  to make configuration files simpler and evident in this respect. In
  this sake, also, indentation was considered.

- Previously, the header information was stored in
  files/centos-design/header.html file. Now it is in
  templates/header.html.j2.

### CODE REVIEW

**Comment by arrfab** [comment]
I'll review those proposed changes soon and I like the idea of using header.html.j2.
But if we want to customize it per vhost, with different title, I'll probably change your proposal after having merged it, to distribute the file as unique header per vhost, in case servers have multiple vhosts (and it's the case in the centos infra), so that each vhost would use a different generated header.

**Comment by arrfab** [comment]
and also in the same idea, let's add a custom block that can be added per vhost if defined ? 
That would be an easy way to have message displayed, like what we have for debuginfo,vault vhosts.
So something like {{ httpd_html_content_block }}, just inserted before the httpd/apache mod_autoindex view.
That block can be empty by default, but used per vhost/ansible-role when importing this ansible-role-httpd.

**Comment by arrfab** [comment]
What about we use those variables : 
```
httpd_html_autoindex_title: "CentOS"
httpd_html_autoindex_content: ""
```

Then in the .j2 we can have {{ httpd_html_autoindex_content }} just before content constructed by httpd is shown (to display some text)

And for the template: action, let's also use different name, so that we can have multiple .html file on nodes hosting multiple roles/vhosts : 

something (To be tested), like : 
```
dest: /var/www/cento-design/header-{{ httpd_html_index_title | lower | replace(" ","-") }}.html
```

So using the title as unique name.
Opinions ?

**Comment by areguera** [comment]
It looks very well @arrfab. I am implementing it.

**Comment by areguera** [comment]
@arrfab , how are we providing the value to these variables? Using extra_vars from the command-line when the playbook is triggered or just hardcoded in the role tasks themselves?

Considering we have defaults and specific values to each case, we may need to duplicate variable definitions. For example, in vhost-people.yml we first create the `header.html` and `users.html` list, then we concatenate them with `footer.html`. In the first case, we have to set the title information in the task vars in order to be sure the correct header is used. Also set the same title information when we concatenate to consider the right path of `header.html`.

**Comment by arrfab** [comment]
It would be defined through import_role.
One example on how httpd role is imported for other role (like mirror.centos.org):
```
- import_role:
    name: httpd
```
And then we can use it with:
```
- import_role:
    name: httpd
  vars:
    httpd_html_autoindex_title: "CentOS Mirror"
    httpd_html_autoindex_content: "Here are the supported CentOS Releases"
```

Just an example, as in content, we can inject html code, etc, but you have the idea

**Comment by areguera** [comment]
So, it is safe to remove the vars definitions from tasks.

**Comment by arrfab** [comment]
Looks good, let me merge and deploy on some nodes

**Pull request merged**
